### ISSUE TITLE
GCC fails while parsing header(s)

### ISSUE THREAD

**Issue by helmesjo** [build2-packaging/google-benchmark#1]
Hi! 
First off: Thanks for this! Was about to write my own package but you've saved me the trouble. ;)

Anyways, building with GCC spews out a bunch of `error: inconsistent C++ compiler behavior` errors. To get something more sensical, run with `config.cc.coptions+="-fdirectives-only"` (as suggested by the build2 info output) and you see this:

```c
google-benchmark/src/../include/benchmark/benchmark.h:1151:49: error: __COUNTER__ expanded inside directive with -fdirectives-only
 1151 | #if defined(__COUNTER__) && (__COUNTER__ + 1 == __COUNTER__ + 0)
```

@boris-kolpackov any idea how to circumvent this? Or is it just a GCC bug? Running with `GCC 11.2.0` (same in `GCC 10.3.0`, haven't tried others). Clang works fine.

**Edit:**
Actually, just building using `cmake` + `GCC` works, so not a GCC bug.

**Comment by Swat-SomeBug** [comment]
Hi @helmesjo, this seems to be a precaution that GCC is taking. There is an interesting discussion on how this could be solved, on the build2 slack channel. There is a fix available on the `gcc-patch` branch which solves the issue.
However, the fix is not ideal with respect to maintenance and behaviour when the package is installed.
There is in an edge case where one could compile+install using GCC and then consume the package using Clang on Linux.

Could you try using `gcc-patch` branch (change in manifest to use this branch)? Currently there is less experience with the patch, and your feedback would help gain confidence before merging it to `master`.

**Comment by helmesjo** [comment]
@Swat-SomeBug Ah, thanks. Should've spotted that one.

Just tested with GCC & Clang, both build fine and tests pass (I think, there a lots of them but at least no crash).

**Comment by boris-kolpackov** [comment]
I just re-read that Slack thread (requires login: https://cpplang.slack.com/archives/CDJ0Z991S/p1634245567085300) and while I personally would have just dropped the `&& (__COUNTER__ + 1 == __COUNTER__ + 0)` part, perhaps the middle ground would be to only drop it for GCC? That is, make it something along these lines:

```c++
//#if defined(__COUNTER__) && (__COUNTER__ + 1 == __COUNTER__ + 0)
#if defined(__COUNTER__) && (defined(__GNUC__) || (__COUNTER__ + 1 == __COUNTER__ + 0))
#define BENCHMARK_PRIVATE_UNIQUE_ID __COUNTER__
#else
#define BENCHMARK_PRIVATE_UNIQUE_ID __LINE__
#endif
```

We know that GCC has proper `__COUNTER__` support so there is no reason for anyone to redefine this macro.

**Comment by Swat-SomeBug** [comment]
Hi @boris-kolpackov, the current patch does the same as what you suggest, in principle.
But it does it a little more defensively, by guarding the full `#ifdef` with another macro, currently called `_NO_COUNTER_INC_TEST`.
This define is the set and propagated to consumers in the build script when `GCC` is used for build/install.

`_NO_COUNTER_INC_TEST` has a role very similar to `__GNUC__` in your code snippet.
My primary reason to use the new macro was to allow users the capability to enable the test explicitly incase it was really required to hack the installed public header, when consuming without `build2` or `pkg-config`.

**Comment by boris-kolpackov** [comment]
Yes, though this feels like the wrong tradeoff to me: you are trading a much more likely scenario where someone, say, builds/installs with Clang and then uses with GCC vs someone needing to force this check for some reason. Why not inverse this and have a macro to force the check rather than to disable the check, something along these lines:

```c++
#if defined(__COUNTER__) && ((defined(__GNUC__) && !defined(BENCHMARK_FORCE_COUNTER_INC_TEST)) || (__COUNTER__ + 1 == __COUNTER__ + 0))
```

(Also notice how I prefixed the macro with `BENCHMARK_` to make it specific to this library; in fact `_NO_COUNTER_INC_TEST` is a reserved (by C/C++) identifier because it start with an underscore and an uppercase letter).

**Comment by Swat-SomeBug** [comment]
Yes, you are right. This simplifies the situation but still allows the consumers to hack around if really needed.
I will implement it and merge it in!!!
Thanks a lot @boris-kolpackov
